apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: my-app:latest  
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid  
          readinessProbe:
            httpGet:
              path: /healthz  
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz  
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
